[package]
name = "yellowpages-proof-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"], default-features = false }
base64 = "0.22"
