version = 1
name = "yellowpages-proof-service"
uuid = "enclave_7c8330e13b41"
app_uuid = "app_0883710b5780"
team_uuid = "team_2fdd8fada14e"
debug = false
dockerfile = "./Dockerfile"
api_key_auth = false
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []

[egress]
enabled = false

[signing]
certPath = "./cert.pem"
keyPath = "./key.pem"
