name: Dev Deploy Enclave

on:
  push:
    paths:
      - .github/workflows/dev-deploy-enclave.yaml
      - src/**
      - Dockerfile
      - enclave.toml
      - Cargo.*

jobs:
  deploy-enclave:
    name: Dev Deploy Enclave
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Ensure Clippy is available
        run: rustup component add clippy

      - name: Ensure rustfmt is available
        run: rustup component add rustfmt

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check Rust formatting
        run: cargo fmt -- --check

      - name: Dev Deploy Enclave
        env:
          EV_API_KEY: ${{ secrets.DEV_EV_API_KEY_WITH_ENCLAVE_DEPLOY_PERMISSION }}
          EV_APP_UUID: ${{ secrets.DEV_EV_APP_UUID }}
          EV_ENCLAVE_SIGNING_CERT: ${{ secrets.DEV_EV_ENCLAVE_SIGNING_CERT }}
          EV_ENCLAVE_SIGNING_KEY: ${{ secrets.DEV_EV_ENCLAVE_SIGNING_KEY }}
        run: |
          curl https://cli.evervault.com/v4/install -sL | sh
          echo "$EV_ENCLAVE_SIGNING_CERT" > cert.pem
          echo "$EV_ENCLAVE_SIGNING_KEY" > key.pem
          ev enclave deploy -v
